preload = /home/dee/Downloads/wallpapers/nature-beauty-silhouettes-against-majestic-skies-generative-ai.jpg

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
wallpaper =,/home/dee/Downloads/wallpapers/nature-beauty-silhouettes-against-majestic-skies-generative-ai.jpg

#enable splash text rendering over the wallpaper
splash = true

#fully disable ipc
# ipc = off

